# Generated by Django 2.1.1 on 2018-09-13 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, verbose_name='Imię')),
                ('last_name', models.CharField(default='', max_length=128, verbose_name='Nazwisko')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='actors')),
                ('biography', models.CharField(blank=True, default='', max_length=500, verbose_name='Biografia')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czas_trwania', models.IntegerField(default=0)),
                ('rodzaj', models.IntegerField(choices=[(0, 'nieznany'), (1, 'komedia'), (2, 'dramat'), (3, 'sci-fi'), (4, 'kryminal')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(default='')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('released', models.DateField(blank=True, null=True)),
                ('imdb_rating', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='filmy')),
                ('info', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ExtraInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default='', max_length=500, verbose_name='Komentarz')),
                ('stars', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, verbose_name='Ocena')),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Movie')),
            ],
        ),
        migrations.AddField(
            model_name='actor',
            name='movie',
            field=models.ManyToManyField(to='main.Movie'),
        ),
    ]
